version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  ignore:
    # Ignore some updates to the 'okhttp' package
    # Ignore only new versions for >= 3.13.x
    - dependency-name: "com.squareup.okhttp3:okhttp"
      versions: ">= 3.13.0"
    # Ignore all updates to the 'locus' package
    # minSdk=21 in version 0.9.x
    # update in work
    - dependency-name: "com.asamm:locus-api-android"
    # Ignore all updates to the 'android-gif-drawable' package
    # minSdk=17 from version 1.2.16
    - dependency-name: "pl.droidsonroids.gif:android-gif-drawable"
    # Ignore all updates to the com.google.zxing:core
    # minSdk=19 from version 3.3.1
    # used for downgrade zxing-android-embedded
    - dependency-name: "com.google.zxing:core"
