commit_message: '[skip ci]' 
files:
  - source: /src/main/res/values/string*.xml
    ignore:
      - strings_not_translatable.xml
      - strings_pref_languages.xml
      - string_pref_keys.xml
    translation: /src/main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
  - source: /_data/playstore/source/*.txt
    translation: /_data/playstore/translated/%language%/%original_file_name%    
    content_segmentation: 1
