blank_issues_enabled: true
contact_links:
  - name: 3. Contact our WhereYouGo support team
    url: https://mailxto.com/a8vgq3
    about: If you have questions regarding the usage of WhereYouGo you should contact our support team by mail instead. Click open to proceed.
